/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as ConnectAccountIndexRouteImport } from './routes/connect-account/index'
import { Route as AskAgentIndexRouteImport } from './routes/ask-agent/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as PagesPageIdRouteImport } from './routes/pages/$pageId'
import { Route as NotesIdRouteImport } from './routes/notes/$id'
import { Route as DocumentsPagesRouteImport } from './routes/documents/pages'
import { Route as DocumentsChatRouteImport } from './routes/documents/chat'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents/$documentId'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const ConnectAccountIndexRoute = ConnectAccountIndexRouteImport.update({
  id: '/connect-account/',
  path: '/connect-account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskAgentIndexRoute = AskAgentIndexRouteImport.update({
  id: '/ask-agent/',
  path: '/ask-agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPageIdRoute = PagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsPagesRoute = DocumentsPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsChatRoute = DocumentsChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => DocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/wiki': typeof WikiRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/documents/chat': typeof DocumentsChatRoute
  '/documents/pages': typeof DocumentsPagesRoute
  '/notes/$id': typeof NotesIdRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/ask-agent/': typeof AskAgentIndexRoute
  '/connect-account/': typeof ConnectAccountIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/search/': typeof SearchIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wiki': typeof WikiRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/documents/chat': typeof DocumentsChatRoute
  '/documents/pages': typeof DocumentsPagesRoute
  '/notes/$id': typeof NotesIdRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/ask-agent': typeof AskAgentIndexRoute
  '/connect-account': typeof ConnectAccountIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/login': typeof LoginIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/search': typeof SearchIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/wiki': typeof WikiRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/documents/chat': typeof DocumentsChatRoute
  '/documents/pages': typeof DocumentsPagesRoute
  '/notes/$id': typeof NotesIdRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/ask-agent/': typeof AskAgentIndexRoute
  '/connect-account/': typeof ConnectAccountIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/search/': typeof SearchIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/wiki'
    | '/documents/$documentId'
    | '/documents/chat'
    | '/documents/pages'
    | '/notes/$id'
    | '/pages/$pageId'
    | '/share/$token'
    | '/ask-agent/'
    | '/connect-account/'
    | '/documents/'
    | '/login/'
    | '/organizations/'
    | '/reset-password/'
    | '/search/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/wiki'
    | '/documents/$documentId'
    | '/documents/chat'
    | '/documents/pages'
    | '/notes/$id'
    | '/pages/$pageId'
    | '/share/$token'
    | '/ask-agent'
    | '/connect-account'
    | '/documents'
    | '/login'
    | '/organizations'
    | '/reset-password'
    | '/search'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/documents'
    | '/wiki'
    | '/documents/$documentId'
    | '/documents/chat'
    | '/documents/pages'
    | '/notes/$id'
    | '/pages/$pageId'
    | '/share/$token'
    | '/ask-agent/'
    | '/connect-account/'
    | '/documents/'
    | '/login/'
    | '/organizations/'
    | '/reset-password/'
    | '/search/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  WikiRoute: typeof WikiRoute
  NotesIdRoute: typeof NotesIdRoute
  PagesPageIdRoute: typeof PagesPageIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
  AskAgentIndexRoute: typeof AskAgentIndexRoute
  ConnectAccountIndexRoute: typeof ConnectAccountIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/connect-account/': {
      id: '/connect-account/'
      path: '/connect-account'
      fullPath: '/connect-account/'
      preLoaderRoute: typeof ConnectAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-agent/': {
      id: '/ask-agent/'
      path: '/ask-agent'
      fullPath: '/ask-agent/'
      preLoaderRoute: typeof AskAgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$pageId': {
      id: '/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof PagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/pages': {
      id: '/documents/pages'
      path: '/pages'
      fullPath: '/documents/pages'
      preLoaderRoute: typeof DocumentsPagesRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/chat': {
      id: '/documents/chat'
      path: '/chat'
      fullPath: '/documents/chat'
      preLoaderRoute: typeof DocumentsChatRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  DocumentsChatRoute: typeof DocumentsChatRoute
  DocumentsPagesRoute: typeof DocumentsPagesRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  DocumentsChatRoute: DocumentsChatRoute,
  DocumentsPagesRoute: DocumentsPagesRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  WikiRoute: WikiRoute,
  NotesIdRoute: NotesIdRoute,
  PagesPageIdRoute: PagesPageIdRoute,
  ShareTokenRoute: ShareTokenRoute,
  AskAgentIndexRoute: AskAgentIndexRoute,
  ConnectAccountIndexRoute: ConnectAccountIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
